name: Build App

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/keithlinneman/build-system@sha256:fcbdbd4ed9d44b9b2886a7c68a2c5e963e81198424db0428aafe5761de3acfff
    steps:
      - uses: actions/checkout@v4

      - name: Configure git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::682033464915:role/app-linnemanlabs-web-build
          aws-region: us-east-2

      - name: Build and release
        run: |
          /build-system/build.sh \
            --repo . \
            --ref ${{ github.sha }} \
            --track stable
